In [3]:
import numpy as np 
import math
import matplotlib.pyplot as plt

#Defining constants (in atomic units) and Discretize the System
h_bar = 1
m = 1
L = 1 #1 Bohr radius
n = 2000
grid = np.linspace(-L/2, L/2, n)

In [4]:
#Constucting the Laplacian matrix
import numpy as np
lp_matrix = np.matrix([[-2, 1, 0, 0, 0], [1, -2, 1, 0, 0], [0, 1, -2, 1, 0], [0, 0, 1, -2, 1], [0, 0, 0, 1, -2]])

dx = (1 / (n-1) )
laplacian = (1/((dx)**2)) * (lp_matrix)      
print(laplacian)

[[-7992002.  3996001.        0.        0.        0.]
 [ 3996001. -7992002.  3996001.        0.        0.]
 [       0.  3996001. -7992002.  3996001.        0.]
 [       0.        0.  3996001. -7992002.  3996001.]
 [       0.        0.        0.  3996001. -7992002.]]


In [7]:
#Constructing Hamiltonian Matrix
hamiltonian_matrix = -((h_bar**2) / (2 * m)) * laplacian
print(hamiltonian_matrix)

[[ 3996001.  -1998000.5        0.         0.         0. ]
 [-1998000.5  3996001.  -1998000.5        0.         0. ]
 [       0.  -1998000.5  3996001.  -1998000.5        0. ]
 [       0.         0.  -1998000.5  3996001.  -1998000.5]
 [       0.         0.         0.  -1998000.5  3996001. ]]


In [9]:
#Solve for Eigenvalues and Eigenvectors, sorting eigenvalues and extracting first 7 energy levels
eigenvalues, eigenvectors = (np.linalg.eig(hamiltonian_matrix))
sorted_values = np.argsort(eigenvalues)                     #Sort eigenvalues/vectors by indices
eigenvalues = eigenvalues[sorted_values]
eigenvectors = eigenvectors[:, sorted_values]

eigenvalues_7 = eigenvalues[:7]
eigenfunctions_7 = eigenvectors[:, :7]

print("First seven energies (eigenvalues):")
print(eigenvalues_7)

First seven energies (eigenvalues):
[ 535362.62045198 1998000.5        3996001.         5994001.5
 7456639.37954801]


In [14]:
# Extract the first five energy levels and corresponding wavefunctions
num_levels = 5
first_five_eigenvalues = sorted_eigenvalues[:num_levels]
first_five_eigenfunctions = sorted_eigenfunctions[:, :num_levels]

# Plot the first five wavefunctions
plt.figure(figsize=(12, 8))

# Names for the wavefunctions
wavefunction_names = [r'$\psi_1$', r'$\psi_2$', r'$\psi_3$', r'$\psi_4$', r'$\psi_5$']

for i in range(num_levels):
    plt.plot(grid, first_five_eigenfunctions[:, i], label=f'{wavefunction_names[i]} (E = {first_five_eigenvalues[i]:.4f})')

plt.title('First Five Wavefunctions')
plt.xlabel('Position (Bohr radii)')
plt.ylabel('Wavefunction')
plt.legend()
plt.grid(True)
plt.show()

NameError: name 'sorted_eigenvalues' is not defined